export const disabledCompanies = [
    "NEPSE",
    "Preference Share",
    "Commercial Banks",
    "Corporate Debenture",
    "Development Banks",
    "Finance",
    "Hotels And Tourism",
    "Hydro Power",
    "Investment",
    "Life Insurance",
    "Manufacturing and Processing",
    "Microfinance",
    "Mutual Fund",
    "Non Life Insurance",
    "Others",
    "Promoter Share",
    "Tradings",
  ];